name: Go
on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        go:
          - "1.12"
          - "1.13"

    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -v ./...
